version: '0.3'

services:
  web:
    build: .
    depends_on:
      - mysql
    container_name: serverApacheTO
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - .:/var/www/html
    environment:
      - ALLOW_OVERRIDE=true
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=blog
  mysql:
    image: mariadb
    container_name: serverMySQLTO
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=root
    ports:
      - "3333:3306"
    # volumes:
      # - ./ressources/database/bddtotal.sql:/docker-entrypoint-initdb.d/bddtotal.sql
  phpmyadmin:
    image: phpmyadmin
    container_name: serverPHPMyAdminTO
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
    ports:
      - "8002:80"